// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv1pcOl9VGhusCAoD81M5AqSEUOnfQlcw',
    appId: '1:19370311423:web:1b1aa03858bf7830c216ca',
    messagingSenderId: '19370311423',
    projectId: 'brill-prime-app-ef084',
    authDomain: 'brill-prime-app-ef084.firebaseapp.com',
    storageBucket: 'brill-prime-app-ef084.firebasestorage.app',
    measurementId: 'G-2E17QZTB7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMDkmDZahbkPfVUPabFi6bdWgVlPkxgzM',
    appId: '1:19370311423:android:ab4a10097ddb424dc216ca',
    messagingSenderId: '19370311423',
    projectId: 'brill-prime-app-ef084',
    storageBucket: 'brill-prime-app-ef084.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Oj8Q5tPRqS7Sh7wD5xEUhl2YxrKDRF8',
    appId: '1:19370311423:ios:5eb5e5a2ffdf4409c216ca',
    messagingSenderId: '19370311423',
    projectId: 'brill-prime-app-ef084',
    storageBucket: 'brill-prime-app-ef084.firebasestorage.app',
    iosBundleId: 'com.brill.prime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Oj8Q5tPRqS7Sh7wD5xEUhl2YxrKDRF8',
    appId: '1:19370311423:ios:712083e6a3a6f1b6c216ca',
    messagingSenderId: '19370311423',
    projectId: 'brill-prime-app-ef084',
    storageBucket: 'brill-prime-app-ef084.firebasestorage.app',
    iosBundleId: 'com.example.brillPrime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv1pcOl9VGhusCAoD81M5AqSEUOnfQlcw',
    appId: '1:19370311423:web:a031f1040ae095a8c216ca',
    messagingSenderId: '19370311423',
    projectId: 'brill-prime-app-ef084',
    authDomain: 'brill-prime-app-ef084.firebaseapp.com',
    storageBucket: 'brill-prime-app-ef084.firebasestorage.app',
    measurementId: 'G-YH4EGVHQXN',
  );
}